# Generated by Django 4.2.3 on 2023-07-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expectation",
            name="created_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="expectation",
            name="done_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Done At"),
        ),
    ]
